### PR TITLE
Make 1.1.0 release

### PR DESCRIPTION
**Pull request by kilograham**
1.1.0 release

### CODE REVIEW

**Comment by lurch** [comment]
https://github.com/raspberrypi/pico-sdk/releases/tag/1.0.1 was released on 1st Feb - why is this showing commits from 23rd Jan?

**Comment by kilograham** [comment]
> https://github.com/raspberrypi/pico-sdk/releases/tag/1.0.1 was released on 1st Feb - why is this showing commits from 23rd Jan?

because they weren't merged until after

**Comment by lurch** [comment]
Is this superseded by #234 ? :confused:

**Review by Wren6991 — APPROVED** [review]
Will approve this one too, in case github figures out its confusion about identical changes on different hashes once approved

**Review by liamfraser — APPROVED** [review]

**Pull request merged**
