### PR TITLE
Fix Doxygen problems for menu enty 'Files' and accessing a cross reference.

### PR DESCRIPTION
**Pull request by papaathome**
For mor info see also: https://forums.raspberrypi.com/viewtopic.php?p=1977970#p1977970

1. Adding Doxygen log file for warnings.
2. Adding all source to Doxygen. (Might not be a good idea to do on a public server due to thei increase of total volume of data)
3. Adding call and caller grapths. (Might not be a good idea on a public server.)
4. Fix of problems in DoxygenLayout.xml by changing 'problem tags' into comment.
5. Activating menu option 'Files' in DoxygenLayout.xml to get access to a cross reference of names.

### CODE REVIEW

**Comment by kilograham** [comment]
seems like you need to rebase your branch off our develop branch

**Comment by papaathome** [comment]
Sorry if my last action was making things worse.
I have problems with git, not knowing what to do. (I'm a SVN man, always have problems with git, this is my second 'pull request' ever.)

**Comment by lurch** [comment]
@papaathome If you're not familiar with `git`, it might be easiest for you to close this PR (as the "Files changed" tab is now showing unrelated changes), and create a fresh commit and PR working off the `develop` branch instead of off the `master` branch?

**Comment by papaathome** [comment]
@lurch I will follow your advise.

**Pull request closed without merging**
