### PR TITLE
Add "-b <addr>" option to elf2uf2.

### LINKED ISSUE #1071: Add "-b <addr>" option to elf2uf2
The input file is treated as a binary blob to be packaged at the specified address.

Handy when the application expects to find data at a known location in flash.
e.g. Config data, display resources, etc.

### PR DESCRIPTION
**Pull request by esky-software**
The input file is treated as a binary blob to be packaged at the specified address.

Fixes #1071

### CODE REVIEW

**Comment by lurch** [comment]
I may have misunderstood what this is doing, but what if you want an ELF _and_ a binary blob packaged into the same UF2 file?

**Comment by kilograham** [comment]
note this is in back burner as we plan to release an improved tool at some point

**Comment by kilograham** [comment]
converting to draft as we have some upcoming changes which will affect this

**Comment by will-v-pi** [comment]
This has been added to `picotool uf2 convert` (which replaces elf2uf2) as the `-o` option

**Pull request closed without merging**
