### PR TITLE
Add Seeed XIAO RP2040 board

### PR DESCRIPTION
**Pull request by mcauser**
New Seeed board:
https://www.seeedstudio.com/XIAO-RP2040-v1-0-p-5026.html

Not sure about this line:
```
#define PICO_BOOT_STAGE2_CHOOSE_GENERIC_03H 1
```
It comes with a GD25Q16CEIG - 2MB SPI NAND Flash.

Not sure if that is compatible with W25Qxx used on other boards, and if it should be changed to:
```
#define PICO_BOOT_STAGE2_CHOOSE_W25Q080 1
```

### CODE REVIEW

**Comment by lurch** [comment]
It's kinda awkward that you have to go to the wiki page and then look at the schematics to work out what RP2040 pin numbers they've actually used for different things! :confused:  But AFAICT the numbers you've used here look correct :+1:

**Comment by kilograham** [comment]
it sounds like this is not ready to merge, so i have converted it to a draft

**Comment by prplz** [comment]
`GENERIC_03H` and `W25Q080` are both working for me on the seeed board.
The flash is actually [puya P25Q16H](https://datasheet.lcsc.com/lcsc/2006121819_-PUYA--P25Q16H-UXH-IR_C559220.pdf).
Related: https://github.com/adafruit/circuitpython/pull/5519

**Comment by prplz** [comment]
@mcauser `PICO_DEFAULT_LED_PIN` should be 25 (the schematic is outdated or something) and you should set `PICO_DEFAULT_LED_PIN_INVERTED` to 1

**Comment by lurch** [comment]
@mcauser see #691 - I'll leave it up to you and @ryanplusplus to work out what you want to do :slightly_smiling_face:

**Comment by lurch** [comment]
Sounds like #691 supersedes this PR, so I guess this PR should be closed? :shrug:

**Comment by kilograham** [comment]
closing - reopen if need be

**Pull request closed without merging**
