### PR TITLE
stdio_usb improvements

### PR DESCRIPTION
**Pull request by kilograham**
* Use shared IRQ if available to avoid 1ms timer. 
* Allow use of stdio_usb with user's tinyusb setup if it has CDC

### CODE REVIEW

**Comment by kilograham** [comment]
fixes #838

**Review by Wren6991 — APPROVED** [review]

**Comment by eustas** [comment]
Hi. This PR has added a check that callback is executed on the right core... But what is the way to setup default alarm pool to fire on core1? Thanks in advance.

**Comment by thewh1teagle** [comment]
Hi
How can I use it?
I tried to set 
```
pico_enable_stdio_usb(server 1)
```
but got the warning
```
stdio USB was configured along with user use of TinyUSB device mode, but CDC is not enabled
```
Trying to make the PI as HID + Serial at the same time

**Comment by lurch** [comment]
All of the Raspberry Pi engineers are currently on holiday, so if none of the examples at https://github.com/raspberrypi/pico-examples/blob/master/README.md#usb-device help, you'll probably get a quicker response from https://forums.raspberrypi.com/

**Comment by peterharperuk** [comment]
Don't configure stdio to use usb. Use a UART instead

**Comment by thewh1teagle** [comment]
@peterharperuk 
But I want to use the same cable for both HID + CDC (for serial) without special tools.

**Comment by thewh1teagle** [comment]
I found a way to do that and it works. the PICO act as HID + CDC device and I can read serial output in my PC in the same time.
[example here](https://github.com/thewh1teagle/pico-ble-server/tree/usb-hid-cdc-ble)

**Pull request merged**
