### PR TITLE
Doxygen Updates

### PR DESCRIPTION
**Pull request by JamesH65**
Fixed font for examples
Removed extraneous tag in DoxygenLayout.xml
~~Add JAVADOC_BRIEF~~ NOW REMOVED

### CODE REVIEW

**Comment by JamesH65** [comment]
@kilograham @aallan

**Comment by kilograham** [comment]
what does JAVADOC_BRIEF do?

Also unrelated, but that new version number needs a few more pixels space above it - it hurts me!

**Comment by JamesH65** [comment]
It should help with the display of the brief description (according to the user who provided the change)  I saw no difference though. I'll see if I can insert some more pixels on the version!

**Comment by JamesH65** [comment]
I have also used this PR to add some extra spacing to the Doxygen SDK version number, to stop @kilograham eye's from bleeding.

**Comment by kilograham** [comment]
I'm still not convinced about the _BRIEF thing... need input on where it helps.

Also, my eyes are bleeding more... the spacing in question (above the version number) is no better, and now there is a gaping chasm below the version number!

**Comment by JamesH65** [comment]
Odd, the spacing thing it looked fine to me - just increase d the spacing between the SDK line and the version line. Will check again.

I'll remove the brief thing for the moment (tomorrow now) and so we get the rest through.

James

**Comment by lurch** [comment]
Current (online) doxygen ouput:
image

First version of James' PR:
image

Second version of James's PR:
image

(screenshots of Firefox 81 on Linux)

> I'm still not convinced about the _BRIEF thing... need input on where it helps.

There's some context about this [here](https://github.com/raspberrypi/pico-sdk/issues/89), if you've not seen it. I just found up the relevant section of the [Doxygen manual](https://www.doxygen.nl/manual/config.html#cfg_javadoc_autobrief).
But I agree that this _could_ be removed, given that our output at https://raspberrypi.github.io/pico-sdk-doxygen/modules.html currently looks fine as-is.

**Comment by JamesH65** [comment]
I've removed the BRIEF thing, but left the version number things as per the last image above, since that looks fine to me.

**Comment by lurch** [comment]
> I've removed the BRIEF thing

Still says "Add JAVADOC_BRIEF" in the commit-message :wink:

**Comment by JamesH65** [comment]
Fixed.

**Review by lurch — DISMISSED** [review]
LGTM :+1: 
(But perhaps my eyes aren't as sensitive as Graham's!)

**Comment by lurch** [comment]
Argh, I've just noticed that the search-results popup seems to use absolute-positioning or something, which means the new version-number pushes down the search-entry textfield, which means the search-results popup appears over the top of the search-entry box :confused: 

This means if you search for something which doesn't exist, the "No matches" appears **over the top** of where you're typing, making it _very_ difficult to search for something else!
This is what it looks like on the live-version
image

And this is what it looks like now the version-number has pushed things down a bit
image

(there also seems to be no way to "dismiss" or close the search-results popup, but that's a separate issue :wink: )

**Comment by lurch** [comment]
@JamesH65 After a bit of guesswork, this _seems_ to fix the search-popup misalignment I mentioned above:
```patch
--- a/docs/styles.css
+++ b/docs/styles.css
@@ -99,7 +99,7 @@
 }
 #MSearchSelectWindow {
     position: fixed;
-    top: 145px !important;
+    top: 165px !important;
     left: 35px !important;
     border: solid 1px #d4d4d4;
     border-radius: 0;
@@ -118,7 +118,7 @@
 }
 #MSearchResultsWindow {
     position: fixed;
-    top: 145px !important;
+    top: 165px !important;
     left: 35px !important;
     border: solid 1px #d4d4d4;
     border-radius: 0;
```

image

(with the caveat that I don't really know what I'm doing :laughing: )

**Comment by lurch** [comment]
... except of course it needs to be tweaked slightly to take account of the additional padding added in this PR.
```patch
--- a/docs/styles.css
+++ b/docs/styles.css
@@ -99,7 +99,7 @@
 }
 #MSearchSelectWindow {
     position: fixed;
-    top: 145px !important;
+    top: 175px !important;
     left: 35px !important;
     border: solid 1px #d4d4d4;
     border-radius: 0;
@@ -118,7 +118,7 @@
 }
 #MSearchResultsWindow {
     position: fixed;
-    top: 145px !important;
+    top: 175px !important;
     left: 35px !important;
     border: solid 1px #d4d4d4;
     border-radius: 0;
```

**Comment by JamesH65** [comment]
That search box is a PITA. Doesn't go away with ESC.

**Review by lurch — APPROVED** [review]
LGTM :+1: 

image

**Pull request merged**
