### PR TITLE
Add information on targetting the Pico W. Fixes #895

### LINKED ISSUE #895: README doesn't describe how to target Pico W board
Although the pico_w.h board is now present the 'terse' README should probably mention how to target it

### PR DESCRIPTION
**Pull request by lbt**
Now the Pico W is available the ability to target specific boards via cmake defines is a relevant addition to the introductory documentation.

### CODE REVIEW

**Comment by lurch** [comment]
The PDFs are linked to from https://www.raspberrypi.com/documentation/microcontrollers/raspberry-pi-pico.html :slightly_smiling_face:

**Comment by lbt** [comment]
I hope the title and description are now suitable?

Re pdf links - so they are - I couldn't recall how I'd arrived at the pdf docs and was looking for direct links in this repo :)
Is the pdf source public?

**Comment by lurch** [comment]
Nope. The PDFs themselves are licensed under [CC BY-ND](https://creativecommons.org/licenses/by-nd/4.0/) but the source for the PDFs isn't public.

**Comment by kilograham** [comment]
@lurch you had commented this also related to something you were doing

**Comment by lurch** [comment]
ping @aallan Do we have rptl.io links for the new Pico-W-specific PDFs?

**Comment by aallan** [comment]
> I hope the title and description are now suitable?
> 
> Re pdf links - so they are - I couldn't recall how I'd arrived at the pdf docs and was looking for direct links in this repo :) Is the pdf source public?

All the PDF documentation is linked from the microcontroller section of our online documentation, see https://www.raspberrypi.com/documentation/microcontrollers/.

**Comment by aallan** [comment]
> ping @aallan Do we have rptl.io links for the new Pico-W-specific PDFs?

Not sure why we really need them. But I mean, I can create some if you want? 

http://rptl.io/picow-connect -> https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf
http://rptl.io/picow-datasheet -> https://datasheets.raspberrypi.com/picow/pico-w-datasheet.pdf

**Comment by lurch** [comment]
I was thinking it might be useful to add them to https://github.com/raspberrypi/pico-sdk/blob/master/README.md#documentation along with the other short-links. Do you want to add in the `http://rptl.io/picow-connect` link to `README.md` in this PR @lbt ?

(Also, we could/should add them to https://github.com/raspberrypi/pico-sdk/blob/develop/docs/DoxygenLayout.xml and https://github.com/raspberrypi/pico-sdk/blob/develop/docs/weblinks_page.md too? :man_shrugging: )

**Comment by JamesWP** [comment]
This just cost me an hour of debugging with my brand new Pico W board. 😭 

The very first thing you're directed to do via the getting started is creating the blink example and that had me stumped. 

I would go so far as to say, make this a bold gotcha warning on the top part of the readme. or else make it something CMake complains about if not specified.

Yes, eventually I managed to find the parts of the [raspberrypi.com page](https://www.raspberrypi.com/documentation/microcontrollers/c_sdk.html#raspberry-pi-pico-cc-sdk) which reference the pico W needing special configuration. Though even then it references it only in combination with wanting the wifi module to work, which surely isn't somthing I need to pay attention to when trying to get a LED blinking?

**Comment by MrGreensWorkshop** [comment]
I believe adding to CMakeLists.txt file is better than ading as cmake params.
I prefer to put in CMakeLists.txt file. `set(PICO_BOARD pico_w)`

**Review by lurch — APPROVED** [review]

**Review by kilograham — APPROVED** [review]

**Pull request merged**
