### PR TITLE
Update mktime header declaration to match upstream LLVM libc.

### PR DESCRIPTION
**Pull request by Prabhuk**
Fixes:#1971

### CODE REVIEW

**Comment by armandomontanez** [comment]
I'm guessing this isn't backwards-compatible with older toolchain distributions?

**Comment by kilograham** [comment]
.. which it needs to be

**Comment by Prabhuk** [comment]
Thanks for bringing up the compatibility question. I should've added the testing info to the PR description. 
The change is compatible with the old toolchain revision.

I was able to use the current Clang toolchain revision - e894df6392beea3723627329009f3e6d51d16f47 against pico-sdk master branch with this PR's commit cherry-picked. The bazel build was completed successfully.

**Comment by petrhosek** [comment]
`mktime` is now included in [LLVM libc `time.h` header](https://github.com/llvm/llvm-project/blob/98a15c7b0c6ec129d371f0c121dbe9396c4f5609/libc/config/baremetal/arm/entrypoints.txt#L211), so the correct solution here is to delete that declaration altogether, but we also need to bump the toolchain version in [`MODULE.bazel`](https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/MODULE.bazel#L61-L92).

**Comment by petrhosek** [comment]
I opened https://github.com/raspberrypi/pico-sdk/pull/1976 which updates the toolchain.

**Comment by Prabhuk** [comment]
> `mktime` is now included in [LLVM libc `time.h` header](https://github.com/llvm/llvm-project/blob/98a15c7b0c6ec129d371f0c121dbe9396c4f5609/libc/config/baremetal/arm/entrypoints.txt#L211), so the correct solution here is to delete that declaration altogether, but we also need to bump the toolchain version in [`MODULE.bazel`](https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/MODULE.bazel#L61-L92).

That makes sense. @armandomontanez Will there ever be a case in Pigweed presubmits where the patches landed in the "develop" branch here be built with the toolchain revision mentioned in Pigweed's bazel source files?

**Comment by armandomontanez** [comment]
Not automatically. For now, we'll be manually revving the required version of the Pico SDK. There may come a day where we do builds against HEAD of `develop` to learn about breakages sooner, but that's a ways out.

**Comment by Prabhuk** [comment]
> Not automatically. For now, we'll be manually revving the required version of the Pico SDK. There may come a day where we do builds against HEAD of `develop` to learn about breakages sooner, but that's a ways out.

Great! I'll close this PR. I'm assuming when we update the toolchain revision in Pigweed, we will update the PicoSDK revision which includes #1976 to get the presubmits to pass.

**Pull request closed without merging**
