### PR TITLE
Initial Pico/2 W Bazel support

### PR DESCRIPTION
**Pull request by armandomontanez**
Builds out initial Bazel support for Pico W wireless libraries. With these changes, it's now possible to produce working Wifi and Bluetooth applications for Pico W boards.

### CODE REVIEW

**Comment by armandomontanez** [comment]
Okay, marking this as ready for review since it's a pretty big step forward now. I've gotten BLE and Wifi examples working in pico-examples, I'm totally down to send out a PR for that later.

There's still a little more to go:
* MbedTLS hasn't been hooked up/tested.
* FreeRTOS interactions with the wireless libraries hasn't been tested.
* Gatt header compilation works for independent gatt files. If a gatt file depends on another, there's no way to get it (yet).
* Need to properly pin Python PIP dependencies for the gatt header creation.

**Review by kilograham — APPROVED** [review]
thx

**Comment by RyanDraves** [comment]
@armandomontanez, do you have `BUILD` files for the BLE & Wifi examples? I'm able to compile an example, but it's crashing on `cyw43_arch_init` for some unknown reason. I have these config options set:
```
        "--@pico-sdk//bazel/config:PICO_BT_ENABLE_BLE=True",
        "--@pico-sdk//bazel/config:PICO_BOARD=pico_w",
        "--@pico-sdk//bazel/config:PICO_BTSTACK_CONFIG=//project:btstack_config",
```
where `btstack_config` is just pulled from the examples. Is there additional configuration options that need to be set?

Happy to open an issue if that's preferred

**Comment by armandomontanez** [comment]
Try setting `--@pico-sdk//bazel/config:PICO_MULTICORE_ENABLED=False`. I was considering flipping the default to `False` for this reason. Wireless works with multicore support, but IIRC you have to either 1) flip some other configuration flags or 2) be careful about your init order.

I was testing against a bunch of the examples in [pico-examples](https://github.com/raspberrypi/pico-examples), I just put up a draft PR here: https://github.com/raspberrypi/pico-examples/pull/587

**Comment by armandomontanez** [comment]
I filed https://github.com/raspberrypi/pico-sdk/issues/2139 to leave a breadcrumb.

**Comment by RyanDraves** [comment]
Thanks for the tips. I tried adding `--@pico-sdk//bazel/config:PICO_MULTICORE_ENABLED=False` without any luck. I was able to build and run the standalone example from your PR though; I'll go searching for the discrepancy and update here and/or the ticket when I find it

**Comment by RyanDraves** [comment]
I have it building now from my toy examples as well. My last issue was unrelated; `--@pico-sdk//bazel/config:PICO_MULTICORE_ENABLED=False` was the relevant fix. Thanks!

**Pull request merged**
