### PR TITLE
Add stdio_set_chars_available_callback

### PR DESCRIPTION
**Pull request by peterharperuk**
There's currently no way to be notified in a "stdio" agnostic way whether there's an incoming character available. You can poll with getchar_timeout_us, but that's far from ideal.

Add a method that takes a callback to notify that a character might be available.

### CODE REVIEW

**Review by kilograham — COMMENTED** [review]
Actually now i think about it, let's have `PICO_STDIO_USB_SUPPORT_CHARS_AVAILABLE_CALLBACK` #ifdef out all of the function implementations and static vars too, and then add a
`PICO_STDIO_UART_SUPPORT_CHARS_AVAILABLE_CALLBACK` #ifdef too
because it is a bunch (small amount) of new code that is taking up space even if not used

**Comment by peterharperuk** [comment]
Do you want it disabled by default? Currently I made it enabled by default.

**Comment by kilograham** [comment]
i think enabled is fine, people may just want to turn it off

**Comment by peterharperuk** [comment]
Done as requested

**Review by kilograham — APPROVED** [review]

**Pull request merged**
