### PR TITLE
WIP: Add missing btstack files

### LINKED ISSUE #1379: Some btstack files missing
When we update btstack (#1376) we need to add some missing files.

### PR DESCRIPTION
**Pull request by peterharperuk**
Fixes #1379

### CODE REVIEW

**Comment by peterharperuk** [comment]
Needs us to update btstack first

**Review by kilograham — CHANGES_REQUESTED** [review]
small thing, but (and it looks like there are a cople of offenders with md5 and yxml, but the majority of this is in alphabetical order, so best to maintain

**Comment by peterharperuk** [comment]
fixed alpha order and moved the classic file to the right lib!

**Review by kilograham — APPROVED** [review]

**Comment by peterharperuk** [comment]
Oh dear - still says WIP. I thought that would block it.

**Pull request merged**
