### PR TITLE
Update i2c.h

### PR DESCRIPTION
**Pull request by k1r0s**
typo

### CODE REVIEW

**Comment by lurch** [comment]
AFAIK this _isn't_ a typo - see e.g. Figure 87 in the RP2040 datasheet.

**Comment by Wren6991** [comment]
To clarify, PRESETn/presetn is the active-low reset for the I2C block. Text is correct as it stands, but maybe a bit misleading

**Comment by Wren6991** [comment]
I hadn't realised this was an edit to a register header. Those headers are generated from the same source as the SVD and the datasheet listings (and it's important they match) so we can't merge PRs to those files.

Here is the register table in the datasheet:

image

Other relevant parts of the I2C section of the datasheet:

image

image

**Comment by k1r0s** [comment]
lol, I thought it was a typo. Im dumb

**Comment by k1r0s** [comment]
@Wren6991 To clarify I would recommend that the existing text is displayed like so:

```
means once the 'PRESETn' signal is applied
```

**Pull request closed without merging**
