### PR TITLE
Enable 'Files' in Doxygen menu list, added source, caller graph and call graph to Doxigen documentation.

### PR DESCRIPTION
**Pull request by papaathome**
1. Doxyfile.in: added log file to Doxygen for warnings and errors.
2. Doxyfile.in: added call graph and caller graph to Doxygen output.
3. Doxyfile.in: added all source code to Doxygen output. (Probably not a good idea on a public server.)
4. DoxygenLayout.xml: fixed all problem tags by putting them in comment.
5. DoxygenLayout.xml: added menu option 'Files' by making it visible and giving it a title.

### CODE REVIEW

**Comment by papaathome** [comment]
See also: [C/C++ discussion therad](https://forums.raspberrypi.com/viewtopic.php?t=330422)

Kind regards,

**Comment by lurch** [comment]
`100644 → 100755`
No need to mark the files as executable :)

**Comment by lurch** [comment]
> Which file(s)?

According to the "Files changed" tab at the top of this PR, it's both of the files that you've modified.

**Comment by papaathome** [comment]
Not done intentionally.

The git checkout was done on a samba share and is accessable for both my Debian machine and my windows 10 machine. That might be the cause of this change.

**Comment by kilograham** [comment]
cc @aallan @lurch

**Comment by lurch** [comment]
Could you clarify what you mean by "(Probably not a good idea on a public server.)" please?
The Doxygen-output that gets built from this is visible at https://raspberrypi.github.io/pico-sdk-doxygen/

**Comment by aallan** [comment]
The doxygen also gets sucked into our PDF toolchain via XSLT and auto generates a bunch of asciidoc which is built into the Pico C/C++ SDK book. Unclear how this PR would affect that, or the micro site. 

I'd be disinclined to make arbitrary changes here. In the long term we're going to work on the micro site skin, and look at improving the XSLT and the Doxygen to Asciidoc import. 

However the effects of this are unclear. I'd be extremely reluctant to accept this PR without a lot of investigation into the (not public ally visible) knock on effects, which I don't think either @lurch or myself have time for right now. 

Sorry.

**Pull request closed without merging**
