### PR TITLE
SPI Definitions for SparkFun boards

### PR DESCRIPTION
**Pull request by kirk-sfe**
Added the #defines for the default SPI pins on SparkFun boards

### CODE REVIEW

**Review by lurch — APPROVED** [review]
LGTM :+1:

**Comment by lurch** [comment]
Oh, but can you rebase against the `develop` branch please?

**Comment by lurch** [comment]
You also need to click 'Edit' at the top of this PR and change the base branch :wink:

**Comment by kirk-sfe** [comment]
Thanks @lurch - was trying to figure out the rebase process!

**Review by lurch — APPROVED** [review]

**Comment by 2bndy5** [comment]
@lurch I don't see a contributing guidelines in this repo. Do you get tired of asking people to rebase on the develop branch? Or are contributions normally limited to a privileged few?

**Comment by andrum99** [comment]
> @lurch I don't see a contributing guidelines in this repo. Do you get tired of asking people to rebase on the develop branch? Or are contributions normally limited to a privileged few?

Github has a handy feature where you can set up a template for PRs to a repo. I think this would be useful for this repo, since the author is invariably requested to rebase. While this won't make the PR be against a different branch, it would be an opportunity to automatically request the author to rebase against a specific branch, rather than a human having to spend time requesting this for each PR.

**Comment by lurch** [comment]
These are questions for @kilograham . I only ask people to rebase to `develop`, in the hope that they'll be able to do that before Graham then comes online (we're in different timezones) :slightly_smiling_face:

**Comment by kilograham** [comment]
Not a bad idea! Is this issue otherwise OK?

**Comment by 2bndy5** [comment]
@kilograham I feel this PR mostly satisfies #328 (which is also satisfied by PR #343). I'm ok with closing #328 upon merger of this PR.

**Review by kilograham — APPROVED** [review]

**Pull request merged**
