### PR TITLE
Fw compress merge

### PR DESCRIPTION
**Pull request by peterharperuk**
Changes required for wifi/bt firmware compression.

Use uzlib library added to the sdk.

Change bt firmware loading to use the functions provided for this purpose in cyw43-driver. It calls cyw43_get_firmware_funcs to get the list of functions.

### CODE REVIEW

**Comment by kilograham** [comment]
what is the status of this? it says checks are failing but that may have been intermittant

**Comment by peterharperuk** [comment]
It's dependent on this https://github.com/georgerobotics/cyw43-driver/pull/68 which needs reviewing first.
I think Damien is of the opinion that the time it takes to decompress the firmware is not worth the flash saving.

**Comment by kilograham** [comment]
moving to 1.6.0 as it sounds like this won't make 1.5.1

**Comment by kilograham** [comment]
doh; have i not reviewed/merged this yet? sorry!

**Pull request closed without merging**
