### PR TITLE
Attempt to prevent workflows being triggered on forks

### PR DESCRIPTION
**Pull request by lurch**

### CODE REVIEW

**Comment by lurch** [comment]
ping @liamfraser @JamesH65

**Comment by JamesH65** [comment]
LGTM, but why the second change? Is it just removing trailing whitespace?

**Comment by lurch** [comment]
It's not something I changed, but it's something that GitHub/git typically displays as "different" if a file with Windows line-endings is edited on Linux or Mac.

**Comment by JamesH65** [comment]
OK, cool.

**Review by liamfraser — APPROVED** [review]

**Pull request merged**
