### PR TITLE
Fix unexpected (CMake) behavior with PICO_BOARD variable.

### PR DESCRIPTION
**Pull request by tjko**
Changing PICO_BOARD value from "pico_w" to "pico" did not unset PICO_CYW43_SUPPORTED variable. Which could lead CYW43 driver included in builds for "pico".  (See issue https://github.com/raspberrypi/pico-sdk/issues/1046)

_Instructions: (please delete)_
 - _please do not submit against `master`, use `develop` instead_
 - _please make sure there is an associated issue for your PR, and reference it via "Fixes #num" in the description_
 - _please enter a detailed description_

### CODE REVIEW

**Comment by lurch** [comment]
* please do not submit against `master`, use `develop` instead

**Comment by kilograham** [comment]
Does this actually work as expected; I would think you need `FORCE` on the set commands

**Comment by tjko** [comment]
I'm not really familiar with CMake so not sure if this is "correct" way to fix the issue.  But it definitely fixed the issue I was having...

**Comment by kilograham** [comment]
I updated the fix to have the `PICO_CYW43_SUPPORTED` not be a cache variable

**Review by kilograham — APPROVED** [review]

**Pull request merged**
