### PR TITLE
Add wiznet_w5100s_evb_pico support

### PR DESCRIPTION
**Pull request by irinakim12**

### CODE REVIEW

**Comment by lurch** [comment]
"Files changed: 159"

I think you might need to rebase your PR? :wink:

**Comment by irinakim12** [comment]
I think it need to add my PR because I'm going to merge in the micropython reposirory.

**Comment by aallan** [comment]
> I think it need to add my PR…

You need to rebase your PR against the `develop` HEAD before it can be accepted. It will not be accepted as is.

> …because I'm going to merge in the micropython repository.

The MicroPython repo isn't maintained by Raspberry Pi and is not our responsibility.

**Comment by irinakim12** [comment]
> You need to rebase your PR against the `develop` HEAD before it can be accepted. It will not be accepted as is. 
image

Do I have to send a PR with the repository's  Clone branch as **develop**?

 > The MicroPython repo isn't maintained by Raspberry Pi and is not our responsibility. 

If I run the PICO board in MicroPython, the compile machine use it by importing the github of the PICO-SDK.  
Then check if the board exists in the src/boards/include/boards/ path.

**Comment by irinakim12** [comment]
I changed the PR brunch as you advised.
This PR is closed and #666 PR is open.

**Pull request closed without merging**
