### PR TITLE
pioasm: Add JSON output format for machine consumption

### LINKED ISSUE #1393: Feature: `pioasm` should support machine-readable output (JSON)
Several times I've been working with external tooling, such as the great [PIO debugger](https://github.com/soundpaint/rp2040pio/) and wanted to be able to pull information out of the PIO assembly files, like side set and loop targets. A machine-readable output, like JSON, would assist in better integration & developement of external tooling for PIO ASM code.

### PR DESCRIPTION
**Pull request by byteit101**
Fixes #1393

## Not included

 * Symbols and "code blocks". I wasn't sure if they were necessary in the JSON output
 * Instructions are one line, as I wanted to get feedback on this before pulling apart `pio_disassembler.cpp`

## Sample output

```json
{
	"publicSymbols": {
		"In_TOP": 9999
	},
	"programs": [
		{
			"name": "spi_gap0_sample1",
			"wrapTarget": 0,
			"wrap": 4,
			"origin": -1,
			"sideset": {"size": 1, "optional": false, "pindirs": false},
			"publicSymbols": {
			},
			"publicLabels": {
				"lp1_end": 2,
				"end": 5
			},
			"instructions": [
				{"hex": "6001"},
				{"hex": "1040"},
				{"hex": "E080"},
				{"hex": "5001"},
				{"hex": "0083"}
			]
		},
		{
			"name": "spi_gap01_sample0",
			"wrapTarget": 0,
			"wrap": 5,
			"origin": 5,
			"sideset": {"size": 1, "optional": false, "pindirs": false},
			"publicSymbols": {
				"This_is_a_number": 65500
			},
			"publicLabels": {
				"lp1_end": 2,
				"end": 6
			},
			"instructions": [
				{"hex": "6001"},
				{"hex": "1040"},
				{"hex": "E080"},
				{"hex": "B042"},
				{"hex": "4001"},
				{"hex": "1084"}
			]
		}
	]
}
```

### CODE REVIEW

**Comment by kilograham** [comment]
nice; i would think that at least public symbols might be useful

**Comment by byteit101** [comment]
I have updated this to export public symbols and labels. In the interest of evolveablity, I also dropped the "index" and "disassembly" fields for now. They can be added at a later time with better syntax.

After some usage testing, I also changed the programs from a map to a list of named objects.

I also changed it to use camelCase for multi-word keys, except for `sideset` which is one word like in the C API. I'm not sure I like this decision though. Thoughts?

**Comment by byteit101** [comment]
Oh and for reference, here is how I'm using this output at the moment (needs to be updated for latest json syntax): https://github.com/byteit101/rp2040pio/blob/daec15beeb5a16c4b594cde68af66fce585c46f5/app/src/main/java/org/soundpaint/rp2040pio/monitor/commands/Assemble.java#L145-L182

**Review by kilograham — APPROVED** [review]

**Comment by lurch** [comment]
@byteit101 I've just noticed that this is producing a compiler-warning:
```
/home/andrew/pico-sdk/tools/pioasm/json_output.cpp: In member function ‘virtual int json_output::output(std::__cxx11::string, std::vector<std::__cxx11::basic_string<char> >, const compiled_source&)’:
/home/andrew/pico-sdk/tools/pioasm/json_output.cpp:105:132: warning: too many arguments for format [-Wformat-extra-args]
                 fprintf(out, "%s\"sideset\": {\"size\": 0, \"optional\": false, \"pindirs\": false},\n", tabs, program.origin.get());
```

**Comment by byteit101** [comment]
@lurch Oh nice find! I can submit a new PR in a few hours, but the correct resolution is to delete the last arg (`, program.origin.get()`) as it looks like I copy-pasted and forgot to remove the template.

**Comment by byteit101** [comment]
I added this fix as https://github.com/byteit101/pico-sdk/commit/878883ef997c9aadf5b7fc11dac57dde3d9360ad and created a PR of https://github.com/raspberrypi/pico-sdk/pull/1625

**Pull request merged**
