### PR TITLE
Mesh support

### PR DESCRIPTION
**Pull request by peterharperuk**

### CODE REVIEW

**Comment by peterharperuk** [comment]
https://github.com/raspberrypi/pico-sdk/issues/1691

**Comment by peterharperuk** [comment]
Seems harmless enough

**Comment by kilograham** [comment]
Do we have documetation listing the individual `pico_btstack_` libraries somewhere?

**Comment by peterharperuk** [comment]
> Do we have documetation listing the individual pico_btstack_ libraries somewhere?

Ah ha - seems we do. https://www.raspberrypi.com/documentation/pico-sdk/networking.html#group_pico_btstack
I will check it's up to date and add this.

**Review by kilograham — APPROVED** [review]

**Pull request merged**
