### PR TITLE
fix #if in hardware/structs/dma.h

### PR DESCRIPTION
**Pull request by majbthrd**
I suspect the user's intent was to use "PARAM_ASSERTIONS_ENABLED_DMA" (default setting generated on lines 17-18).

### CODE REVIEW

**Review by kilograham — COMMENTED** [review]
it is correct as is (as that is a macro that checks PARAM_ASSERTIONS_ENABLED_DMA amongst other stuff)

**Comment by lurch** [comment]
> as that is a macro ...

Defined here: https://github.com/raspberrypi/pico-sdk/blob/master/src/common/pico_base/include/pico/assert.h#L32

**Comment by majbthrd** [comment]
In that case, let me suggest a different approach.  I’ve updated the PR to move these inline functions from:

./src/rp2040/hardware_structs/include/hardware/structs/dma.h

which is a register definition include file where they seem out of place to:

./src/rp2_common/hardware_dma/include/hardware/dma.h

where they are right are home with the DMA driver code that uses them.

**Review by kilograham — COMMENTED** [review]
Yes this is really where the belong, thanks

Not 100% sure why they were there to begin with - perhaps historical. Worth checking it doesn't break compilation of pico-examples, pico-extras, pico-playground (we're currently working on getting our CI re-setup after our move of everything to public github)

**Review by kilograham — APPROVED** [review]

**Pull request merged**
